export const gameVersions = [
  { value: "red-blue", label: "Red & Blue" },
  { value: "yellow", label: "Yellow" },
  { value: "gold-silver", label: "Gold & Silver" },
  { value: "crystal", label: "Crystal" },
  { value: "ruby-sapphire", label: "Ruby & Sapphire" },
  { value: "emerald", label: "Emerald" },
  { value: "firered-leafgreen", label: "FireRed & LeafGreen" },
  { value: "diamond-pearl", label: "Diamond & Pearl" },
  { value: "platinum", label: "Platinum" },
  { value: "heartgold-soulsilver", label: "HeartGold & SoulSilver" },
  { value: "black-white", label: "Black & White" },
  { value: "black-2-white-2", label: "Black 2 & White 2" },
  { value: "x-y", label: "X & Y" },
  { value: "omega-ruby-alpha-sapphire", label: "Omega Ruby & Alpha Sapphire" },
  { value: "sun-moon", label: "Sun & Moon" },
  { value: "ultra-sun-ultra-moon", label: "Ultra Sun & Ultra Moon" },
  { value: "sword-shield", label: "Sword & Shield" },
  { value: "brilliant-diamond-shining-pearl", label: "Brilliant Diamond & Shining Pearl" },
  { value: "legends-arceus", label: "Legends Arceus" },
  { value: "scarlet-violet", label: "Scarlet & Violet" },
]
